-- A lexical scanner generated by aflex
with text_io; use text_io;
with mast_lex_dfa; use mast_lex_dfa; 
with mast_lex_io; use mast_lex_io; 
--# line 1 "mast_lex.l"
--# line 233 "mast_lex.l"


with MAST_Parser_Tokens; use MAST_Parser_Tokens;
with Var_Strings; use Var_Strings;
with Symbol_Table; use Symbol_Table;
package MAST_Lex is

    function YYlex return Token;

end MAST_Lex;
