with Gtk.Dialog; use Gtk.Dialog;
with Gtk.Box; use Gtk.Box;
with Gtk.Button; use Gtk.Button;
with Gtk.Box; use Gtk.Box;
with Gtk.Alignment; use Gtk.Alignment;
with Gtk.Label; use Gtk.Label;
with Gtk.Combo; use Gtk.Combo;
with Gtk.GEntry; use Gtk.GEntry;
with Gtk.Frame; use Gtk.Frame;
with Gtk.Notebook; use Gtk.Notebook;
with Gtk.Scrolled_Window; use Gtk.Scrolled_Window;
with Gtk.Clist; use Gtk.Clist;
package Dialog_Event_Pkg is

   type Dialog_Event_Record is new Gtk_Dialog_Record with record
      Dialog_Vbox1 : Gtk_Vbox;
      Dialog_Action_Area1 : Gtk_Hbox;
      Button_Close_Tr : Gtk_Button;
      Vbox4 : Gtk_Vbox;
      Alignment5 : Gtk_Alignment;
      Hbox3 : Gtk_Hbox;
      Label32 : Gtk_Label;
      Combo_Tr_Transaction : Gtk_Combo;
      Entry_Tr_Transaction : Gtk_Entry;
      Button_All : Gtk_Button;
      Frame5 : Gtk_Frame;
      Notebook2 : Gtk_Notebook;
      Scrolledwindow3 : Gtk_Scrolled_Window;
      Clist_Global_Rt : Gtk_Clist;
      Labelt44 : Gtk_Label;
      Label44 : Gtk_Label;
      Label45 : Gtk_Label;
      Label46 : Gtk_Label;
      Label47 : Gtk_Label;
      Label48 : Gtk_Label;
      Label40 : Gtk_Label;
      Label60 : Gtk_Label;
      Scrolledwindow4 : Gtk_Scrolled_Window;
      Clist_Jitters : Gtk_Clist;
      Label49 : Gtk_Label;
      Labelt49 : Gtk_Label;
      Label50 : Gtk_Label;
      Label51 : Gtk_Label;
      Label52 : Gtk_Label;
      Label43 : Gtk_Label;
      Scrolledwindow5 : Gtk_Scrolled_Window;
      Clist_Blocking : Gtk_Clist;
      Labelt53 : Gtk_Label;
      Label53 : Gtk_Label;
      Label54 : Gtk_Label;
      Label55 : Gtk_Label;
      Label41 : Gtk_Label;
      Label63 : Gtk_Label;
      Scrolledwindow6 : Gtk_Scrolled_Window;
      Clist_Local_Rt : Gtk_Clist;
      Labelt56 : Gtk_Label;
      Label56 : Gtk_Label;
      Label57 : Gtk_Label;
      Label58 : Gtk_Label;
      Label59 : Gtk_Label;
      Label42 : Gtk_Label;
      Label61 : Gtk_Label;
      Label62 : Gtk_Label;
      Scrolledwindow7 : Gtk_Scrolled_Window;
      Clist_Suspensions : Gtk_Clist;
      Labelt64 : Gtk_Label;
      Label65 : Gtk_Label;
      Label66 : Gtk_Label;
      Label67 : Gtk_Label;
      Label68 : Gtk_Label;
      Scrolledwindow8 : Gtk_Scrolled_Window;
      Clist_Local_Miss_Ratios : Gtk_Clist;
      Labelt69 : Gtk_Label;
      Label70 : Gtk_Label;
      Label71 : Gtk_Label;
      Label72 : Gtk_Label;
      Label80 : Gtk_Label;
      Label73 : Gtk_Label;
      Scrolledwindow9 : Gtk_Scrolled_Window;
      Clist_Global_Miss_Ratios : Gtk_Clist;
      Labelt74 : Gtk_Label;
      Label75 : Gtk_Label;
      Label76 : Gtk_Label;
      Label77 : Gtk_Label;
      Label78 : Gtk_Label;
      Label79 : Gtk_Label;
      Label81 : Gtk_Label;
   end record;
   type Dialog_Event_Access is access all Dialog_Event_Record'Class;

   procedure Gtk_New (Dialog_Event : out Dialog_Event_Access);
   procedure Initialize (Dialog_Event : access Dialog_Event_Record'Class);

   Dialog_Event : Dialog_Event_Access;

end Dialog_Event_Pkg;
