with Gtk.Window; use Gtk.Window;
with Gtk.Box; use Gtk.Box;
with Gtk.Pixmap; use Gtk.Pixmap;
with Gtk.Label; use Gtk.Label;
with Gtk.Table; use Gtk.Table;
with Gtk.GEntry; use Gtk.GEntry;
with Glib.Unicode; use Glib.Unicode;
with Gtk.Button; use Gtk.Button;
with Gtk.Combo; use Gtk.Combo;
with Gtk.List_Item; use Gtk.List_Item;
with Gtk.Frame; use Gtk.Frame;
with Gtk.Check_Button; use Gtk.Check_Button;
with Gtk.Alignment; use Gtk.Alignment;
with Gtk.Image; use Gtk.Image;
package Mast_Analysis_Pkg is

   type Mast_Analysis_Record is new Gtk_Window_Record with record
      Vbox1 : Gtk_Vbox;
      Hbox1 : Gtk_Hbox;
      Pixmap1 : Gtk_Pixmap;
      Vbox2 : Gtk_Vbox;
      Pixmap2 : Gtk_Pixmap;
      Title_2 : Gtk_Label;
      Hbox3 : Gtk_Hbox;
      Table1 : Gtk_Table;
      Label6 : Gtk_Label;
      Label8 : Gtk_Label;
      Output_File : Gtk_Entry;
      Label7 : Gtk_Label;
      Hbox6 : Gtk_Hbox;
      Vbox5 : Gtk_Vbox;
      Input_File : Gtk_Entry;
      Label12 : Gtk_Label;
      Hbox8 : Gtk_Hbox;
      Default : Gtk_Button;
      Blank : Gtk_Button;
      Input_File_Selection : Gtk_Button;
      Directory_Entry : Gtk_Entry;
      Tool : Gtk_Combo;
      Listitem857 : Gtk_List_Item;
      Listitem858 : Gtk_List_Item;
      Listitem859 : Gtk_List_Item;
      Listitem860 : Gtk_List_Item;
      Listitem861 : Gtk_List_Item;
      Listitem862 : Gtk_List_Item;
      Listitem863 : Gtk_List_Item;
      Listitem864 : Gtk_List_Item;
      Listitem865 : Gtk_List_Item;
      Frame1 : Gtk_Frame;
      Vbox3 : Gtk_Vbox;
      Label9 : Gtk_Label;
      Table2 : Gtk_Table;
      Verbose : Gtk_Check_Button;
      Ceilings : Gtk_Check_Button;
      Priorities : Gtk_Check_Button;
      Hbox5 : Gtk_Hbox;
      Label10 : Gtk_Label;
      Prio_Assign_Technique : Gtk_Combo;
      Listitem950 : Gtk_List_Item;
      Listitem951 : Gtk_List_Item;
      Listitem952 : Gtk_List_Item;
      Listitem953 : Gtk_List_Item;
      Listitem954 : Gtk_List_Item;
      Destination_File : Gtk_Entry;
      Operation_Name : Gtk_Entry;
      Destination : Gtk_Check_Button;
      Slacks : Gtk_Check_Button;
      Operation_Slack : Gtk_Check_Button;
      View_Results : Gtk_Check_Button;
      Alignment3 : Gtk_Alignment;
      Hbox2 : Gtk_Hbox;
      Alignment1 : Gtk_Alignment;
      Hbox12 : Gtk_Hbox;
      Go_Button : Gtk_Button;
      Alignment19 : Gtk_Alignment;
      Hbox19 : Gtk_Hbox;
      Image5 : Gtk_Image;
      Label35 : Gtk_Label;
      Cancel_Button : Gtk_Button;
      Alignment2 : Gtk_Alignment;
      Hbox11 : Gtk_Hbox;
      Hopa_Params : Gtk_Button;
      Alignment20 : Gtk_Alignment;
      Hbox20 : Gtk_Hbox;
      Image6 : Gtk_Image;
      Label36 : Gtk_Label;
      Annealing_Params : Gtk_Button;
      Alignment21 : Gtk_Alignment;
      Hbox21 : Gtk_Hbox;
      Image7 : Gtk_Image;
      Label37 : Gtk_Label;
      Help_Button : Gtk_Button;
   end record;
   type Mast_Analysis_Access is access all Mast_Analysis_Record'Class;

   procedure Gtk_New (Mast_Analysis : out Mast_Analysis_Access);
   procedure Initialize (Mast_Analysis : access Mast_Analysis_Record'Class);

   Mast_Analysis : Mast_Analysis_Access;

end Mast_Analysis_Pkg;
